# Generated by Django 3.0.8 on 2020-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='imageFile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
