# Generated by Django 3.0.8 on 2020-09-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0002_auto_20200909_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
