# Generated by Django 3.0.8 on 2020-09-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0003_auto_20200909_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
