# Generated by Django 3.0.8 on 2020-09-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
