# Generated by Django 3.0.8 on 2020-09-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0009_auto_20200911_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carousel',
        ),
    ]
