# Generated by Django 3.0.8 on 2020-09-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0010_delete_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
