# Generated by Django 3.0.8 on 2020-09-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0011_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationsName', models.CharField(max_length=50)),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carp.notification')),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=50)),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carp.book')),
            ],
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=50)),
                ('activitylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carp.activity')),
            ],
        ),
    ]
