# Generated by Django 3.0.8 on 2020-09-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0012_activities_books_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='activityName',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='bookName',
            new_name='book_Category',
        ),
    ]
