# Generated by Django 3.0.8 on 2020-09-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0013_auto_20200920_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notificationsName',
            new_name='notification_category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
