# Generated by Django 3.0.8 on 2020-09-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0014_auto_20200920_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='booklist',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='booklist',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='activities',
        ),
        migrations.DeleteModel(
            name='books',
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
