# Generated by Django 3.1.1 on 2020-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0015_auto_20200920_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageFile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
