# Generated by Django 3.1.1 on 2020-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0016_auto_20200926_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
