# Generated by Django 3.1.7 on 2021-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carp', '0017_auto_20200926_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
